DROP TABLE IF EXISTS credit_card CASCADE;

DROP TABLE IF EXISTS transaction_history CASCADE;

DROP TABLE IF EXISTS products_history CASCADE;

DROP TABLE IF EXISTS products CASCADE;

DROP TABLE IF EXISTS users CASCADE;
